#! /bin/bash

DPATH=$HOME/database/$database_name
#echo $DPATH/employee
function deleteRecord {
 while true ;
 do
  echo -e "Enter Table Name: \c"
  read tName
   if [[ ! -f $HOME/database/$database_name/$tName ]]; then
    echo "table does not existed ,choose another name"
   else
   	break
  fi
 done
  echo -e "Enter Column you would like to delete record from: \c"
  read field
  fid=$(awk -F:  '{if ($1 == "'$field'")  print  NR }' $DPATH/.$tName)

  if [[ $fid == "" ]]
  then
  	#echo $DPATH/$tName
    echo "Not Found"
  else
  	echo $fid
    echo -e "Enter record Value: \c"
    read val
    fval=`awk -v a="$fid" -v b="$val" 'BEGIN {FS=":"} { if( $a!= Null ){ tmp=match( $a , b ) ; if(tmp){ print $0 }  } }' $DPATH/$tName`
    
    if [[ $fval == "" ]]
    then
    	echo $fval
    	echo "value not found"
    else
    sed -i -e "/$fval/d" $DPATH/$tName
    echo "Row has been deleted successfully"
	fi
  fi
}

deleteRecord
