#! /bin/bash


function dropTable() {
    read -p "enter table you would like to drop" table
    data=$HOME"/database/"$database_name/$table
    metaD=$HOME"/database/"$database_name/.$table
    if [ -f $data ]
    then
       rm -f $data
       rm -f $metaD 
       echo "table deleted successfully" 
    else
      echo "table doesnot exist"
    fi
}

dropTable 
