#! /bin/bash

echo "you are in database " $database_name
echo "you are in table " $table_name
echo "in commend edit_record" 

function editTable(){
   read -p "enter table you would like to edit" table
   data=$HOME"/database/"$database_name/$table
   metaD=$HOME"/database/"$database_name/.$table
   if [ -f $data ]
   then 
     read -p "enter field you want to edit" field
     find=`sed -n -e "/$field/p" $metaD`
     if [ ! -z "$find" ]
     then
       lines=`awk -v a="$field" 'BEGIN{ FS=":" ; counter=0 ; flag=1 }{ if( $0 != "" && flag==1 ){ counter++ ;if( $1==a ){ flag=0 }  }} END{ print counter } ' $metaD`
       echo $lines
       read -p "enter old value" oldvalue
       read -p "enter new value" value
       output=`awk -v a="$value" -v b="$lines" -v c="$oldvalue"  'BEGIN { FS=":" } { if($b != Null) { tmp=match( $b , c ) ; if(tmp){ gsub($b,a); print $0 }else{ print $0 } } }' $data`
       if [ ! -z "$output" ]
       then  
       echo "$output" > $data 
       else echo "data doesnot match"
       fi
     else
     echo "field not found"
     fi
   else
   echo "table not found"
   fi

}

editTable
