#! /bin/bash

function showTables(){

FILES=$HOME"/database/"$database_name/.*
for f in $FILES
do
  if [ -f $f  ]
  then  
    echo "--------------------------------------------------------------------"
    echo "     Field     |  Type  |  Key  |  Null  |  Defualt Value | Unique |"
    echo "--------------------------------------------------------------------"

    awk -F: '{printf ("%-10s%11s%9s%9s%15s%12s\n", $1,$2,$3,$4,$5,$6)}' $f 
  else
  echo ""
  fi 
done
}

showTables 
